package edu.hw1;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;

public class Task8Test {
    @Test
    @DisplayName("Проверка небъющих коней")
    void testTruthy() {
        byte[][] field = new byte[][] {
            {0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 1, 0, 1, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 1, 0, 0, 0}
        };
        boolean res = Task8.knightBoardCapture(field);
        assertThat(res).isTrue();
    }

    @Test
    @DisplayName("Проверка бъющих коней")
    void testFalsy() {
        byte[][] field = new byte[][] {
            {1, 0, 1, 0, 1, 0, 1, 0},
            {0, 1, 0, 1, 0, 1, 0, 1},
            {0, 0, 0, 0, 1, 0, 1, 0},
            {0, 0, 1, 0, 0, 1, 0, 1},
            {1, 0, 0, 0, 1, 0, 1, 0},
            {0, 0, 0, 0, 0, 1, 0, 1},
            {1, 0, 0, 0, 1, 0, 1, 0},
            {0, 0, 0, 1, 0, 1, 0, 1}
        };
        boolean res = Task8.knightBoardCapture(field);
        assertThat(res).isFalse();
    }

    @Test
    @DisplayName("Проверка на поле с неправильным числом строк")
    void testRowsCheck() {
        byte[][] field = new byte[][] {
            {0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 1, 0, 1, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 1},
        };
        Throwable thrown = catchThrowable(() -> Task8.knightBoardCapture(field));
        assertThat(thrown).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("rows");
    }

    @Test
    @DisplayName("Проверка на поле с неправильным числом столбцов")
    void testColsCheck() {
        byte[][] field = new byte[][] {
            {0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 1, 0, 1, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 1, 0, 0, 0}
        };
        Throwable thrown = catchThrowable(() -> Task8.knightBoardCapture(field));
        assertThat(thrown).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("columns");
    }

    @Test
    @DisplayName("Проверка поля с значением, отличным от 0 и 1")
    void testWrongValue() {
        byte[][] field = new byte[][] {
            {0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, (byte) 255, 0, 1, 0, 0},
            {0, 0, 0, 0, 1, 0, 1, 0},
            {0, 1, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 1, 0, 0, 0}
        };
        Throwable thrown = catchThrowable(() -> Task8.knightBoardCapture(field));
        assertThat(thrown).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("contain");
    }
}
